/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_api_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Template */
        patch: operations["update_template_api_templates__template_id__patch"];
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocks */
        get: operations["list_blocks_api_blocks_get"];
        put?: never;
        /** Create Block */
        post: operations["create_block_api_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Block */
        patch: operations["update_block_api_blocks__block_id__patch"];
        trace?: never;
    };
    "/api/blocks/{block_id}/propagate-progressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propagate Progressions */
        post: operations["propagate_progressions_api_blocks__block_id__propagate_progressions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{block_id}/generate-planned-workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Block Plan */
        post: operations["generate_block_plan_api_blocks__block_id__generate_planned_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planned Workouts */
        get: operations["list_planned_workouts_api_planned_workouts_get"];
        put?: never;
        /** Create Planned Workout */
        post: operations["create_planned_workout_api_planned_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts/{planned_workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Planned Workout */
        patch: operations["update_planned_workout_api_planned_workouts__planned_workout_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa */
        get: operations["spa__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsDailyVolume */
        AnalyticsDailyVolume: {
            /** Date */
            date: string;
            /** Volume */
            volume: number;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Adherence Rate */
            adherence_rate: number;
            /** Planned Count */
            planned_count: number;
            /** Completed Planned Count */
            completed_planned_count: number;
            /** Total Sessions */
            total_sessions: number;
            /** Total Completed Sets */
            total_completed_sets: number;
            /** Total Volume */
            total_volume: number;
            /** Recent Volume */
            recent_volume: components["schemas"]["AnalyticsDailyVolume"][];
        };
        /** AuthUser */
        AuthUser: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** BlockWorkoutExercisePayload */
        BlockWorkoutExercisePayload: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /** Progression Rule Id */
            progression_rule_id?: string | null;
            /**
             * Manual Override
             * @default false
             */
            manual_override: boolean;
        };
        /** BlockWorkoutExerciseRead */
        BlockWorkoutExerciseRead: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Progression Rule Id */
            progression_rule_id?: string | null;
            /** Order Index */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /**
             * Manual Override
             * @default false
             */
            manual_override: boolean;
            /** Progression Snapshot Json */
            progression_snapshot_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** BlockWorkoutPayload */
        BlockWorkoutPayload: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Week Index
             * @default 1
             */
            week_index: number;
            /**
             * Day Index
             * @default 1
             */
            day_index: number;
            /** Notes */
            notes?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["BlockWorkoutExercisePayload"][];
        };
        /** BlockWorkoutRead */
        BlockWorkoutRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Week Index */
            week_index: number;
            /** Day Index */
            day_index: number;
            /** Notes */
            notes?: string | null;
            /** Exercises */
            exercises: components["schemas"]["BlockWorkoutExerciseRead"][];
        };
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            /**
             * Modality
             * @default strength
             */
            modality: string;
            /**
             * Default Measure Type
             * @default reps_weight
             */
            default_measure_type: string;
            /** Notes */
            notes?: string | null;
        };
        /** ExerciseRead */
        ExerciseRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Modality */
            modality: string;
            /** Default Measure Type */
            default_measure_type: string;
            /** Notes */
            notes?: string | null;
            /** Archived At */
            archived_at?: string | null;
        };
        /** GeneratePlannedWorkoutsPayload */
        GeneratePlannedWorkoutsPayload: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * Weeks
             * @default 4
             */
            weeks: number;
        };
        /** GeneratedPlannedWorkoutRead */
        GeneratedPlannedWorkoutRead: {
            /** Id */
            id: string;
            /**
             * Planned Date
             * Format: date
             */
            planned_date: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginPayload */
        LoginPayload: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** PlannedWorkoutCreate */
        PlannedWorkoutCreate: {
            /**
             * Planned Date
             * Format: date
             */
            planned_date: string;
            /** Planned Start Time */
            planned_start_time?: string | null;
            /**
             * Status
             * @default planned
             */
            status: string;
            /** Title */
            title: string;
            /** Notes */
            notes?: string | null;
            /** Training Block Id */
            training_block_id?: string | null;
            /** Block Workout Id */
            block_workout_id?: string | null;
            /** Workout Template Id */
            workout_template_id?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["PlannedWorkoutExercisePayload"][];
        };
        /** PlannedWorkoutDetail */
        PlannedWorkoutDetail: {
            /** Id */
            id: string;
            /**
             * Planned Date
             * Format: date
             */
            planned_date: string;
            /** Planned Start Time */
            planned_start_time?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Notes */
            notes?: string | null;
            /** Training Block Id */
            training_block_id?: string | null;
            /** Block Workout Id */
            block_workout_id?: string | null;
            /** Workout Template Id */
            workout_template_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Exercises */
            exercises: components["schemas"]["PlannedWorkoutExerciseRead"][];
        };
        /** PlannedWorkoutExercisePayload */
        PlannedWorkoutExercisePayload: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /** Progression Rule Id */
            progression_rule_id?: string | null;
            /** Exercise Name Snapshot */
            exercise_name_snapshot?: string | null;
            /** Progression Snapshot Json */
            progression_snapshot_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** PlannedWorkoutExerciseRead */
        PlannedWorkoutExerciseRead: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name Snapshot */
            exercise_name_snapshot: string;
            /** Progression Rule Id */
            progression_rule_id?: string | null;
            /** Order Index */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /** Progression Snapshot Json */
            progression_snapshot_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProgressionRulePayload */
        ProgressionRulePayload: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Rule Type
             * @default fixed_increment
             */
            rule_type: string;
            /** Config Json */
            config_json?: {
                [key: string]: unknown;
            } | null;
            /** Deload Strategy */
            deload_strategy?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ProgressionRuleRead */
        ProgressionRuleRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Rule Type */
            rule_type: string;
            /** Config Json */
            config_json?: {
                [key: string]: unknown;
            } | null;
            /** Deload Strategy */
            deload_strategy?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SetEntryPayload */
        SetEntryPayload: {
            /** Id */
            id?: string | null;
            /** Set Number */
            set_number: number;
            /**
             * Set Type
             * @default work
             */
            set_type: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Reps */
            reps?: number | null;
            /** Weight */
            weight?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance Meters */
            distance_meters?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /** SetEntryRead */
        SetEntryRead: {
            /** Id */
            id: string;
            /** Set Number */
            set_number: number;
            /** Set Type */
            set_type: string;
            /** Completed */
            completed: boolean;
            /** Reps */
            reps?: number | null;
            /** Weight */
            weight?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance Meters */
            distance_meters?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /** TrainingBlockCreate */
        TrainingBlockCreate: {
            /** Name */
            name: string;
            /** Goal */
            goal?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Progression Rules */
            progression_rules?: components["schemas"]["ProgressionRulePayload"][];
            /** Workouts */
            workouts?: components["schemas"]["BlockWorkoutPayload"][];
        };
        /** TrainingBlockDetail */
        TrainingBlockDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Goal */
            goal?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Status */
            status: string;
            /** Progression Rules */
            progression_rules: components["schemas"]["ProgressionRuleRead"][];
            /** Workouts */
            workouts: components["schemas"]["BlockWorkoutRead"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkoutSessionCreate */
        WorkoutSessionCreate: {
            /** Planned Workout Id */
            planned_workout_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Status
             * @default in_progress
             */
            status: string;
            /** Title */
            title: string;
            /** Session Notes */
            session_notes?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["WorkoutSessionExercisePayload"][];
        };
        /** WorkoutSessionDetail */
        WorkoutSessionDetail: {
            /** Id */
            id: string;
            /** Planned Workout Id */
            planned_workout_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Session Notes */
            session_notes?: string | null;
            /** Exercises */
            exercises: components["schemas"]["WorkoutSessionExerciseRead"][];
        };
        /** WorkoutSessionExercisePayload */
        WorkoutSessionExercisePayload: {
            /** Id */
            id?: string | null;
            /** Exercise Id */
            exercise_id?: string | null;
            /** Planned Workout Exercise Id */
            planned_workout_exercise_id?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Exercise Name Snapshot */
            exercise_name_snapshot: string;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Set Entries */
            set_entries?: components["schemas"]["SetEntryPayload"][];
        };
        /** WorkoutSessionExerciseRead */
        WorkoutSessionExerciseRead: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id?: string | null;
            /** Planned Workout Exercise Id */
            planned_workout_exercise_id?: string | null;
            /** Order Index */
            order_index: number;
            /** Exercise Name Snapshot */
            exercise_name_snapshot: string;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
            /** Completed */
            completed: boolean;
            /** Set Entries */
            set_entries: components["schemas"]["SetEntryRead"][];
        };
        /** WorkoutTemplateCreate */
        WorkoutTemplateCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["WorkoutTemplateExercisePayload"][];
        };
        /** WorkoutTemplateExercisePayload */
        WorkoutTemplateExercisePayload: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
        };
        /** WorkoutTemplateExerciseRead */
        WorkoutTemplateExerciseRead: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Order Index */
            order_index: number;
            /** Notes */
            notes?: string | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps */
            target_reps?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Target Duration Seconds */
            target_duration_seconds?: number | null;
            /** Target Distance Meters */
            target_distance_meters?: number | null;
            /** Target Rpe */
            target_rpe?: number | null;
        };
        /** WorkoutTemplateRead */
        WorkoutTemplateRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Exercises */
            exercises: components["schemas"]["WorkoutTemplateExerciseRead"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_api_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocks_api_blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingBlockDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_block_api_blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingBlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingBlockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_block_api_blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingBlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingBlockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propagate_progressions_api_blocks__block_id__propagate_progressions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingBlockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_block_plan_api_blocks__block_id__generate_planned_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePlannedWorkoutsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedPlannedWorkoutRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_planned_workouts_api_planned_workouts_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planned_workout_api_planned_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedWorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_planned_workout_api_planned_workouts__planned_workout_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_workout_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedWorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                workout_tracker_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    spa__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
